# <center> Excercise - NumPy II </center>

### Create a Null vector of size 10 

In [ ]:
import numpy as np
np.info(np.empty)
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

### Create a null vector of size 10 but the fifth value should be 1

In [ ]:
arr=np.zeros(10)
arr[4]=1
arr

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

### create a vector with values ranging from 10 to 49

In [ ]:
np.arange(start=10,stop=49)


array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48])

### reverse a vector (first element becomes last) 

In [ ]:
arr=np.arange(start=10,stop=49)
arr[::-1]

array([48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33, 32,
       31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16, 15,
       14, 13, 12, 11, 10])


### Create a 3 X 3 matrix with values ranging from 0 to 8

In [ ]:
arr=np.arange(start=0,stop=9)
arr.resize((3,3))
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

### Create 3 X 3 identity matrix

In [ ]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

### Find indices of non zero element from [1, 2, 0, 0, 4, 0]

In [ ]:
q=0
arr=[1,2,0,0,4,0]
for i in arr:
  if(i!=0):
    print(q)
    q+=1

0
1
2


### Create a random vector of size 30 and find the mean value

### Create a 8 X 8 matrix and fill it with a checkboard pattern

In [ ]:
arr=np.zeros((8,8))
arr[1::2,::2]=1
arr[::2,1::2]=1
arr

array([[0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.]])

### Multiply a 5 X 3 matrix by 3 X 2 matrix ( real matrix product ) 

In [ ]:
arr1=np.array([1,2,3])
arr1=np.resize(5,2)
arr2=np.array([1,2,3])
arr2=np.resize(3,2)
np.dot(arr1,arr2)

30

### Create a 2d array with 1 on the border and 0 inside

In [ ]:
arr=np.ones((5,5))
arr[1:-1,1:-1]=0
arr

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

### Create a 10 X 10 array with random values and find the minimum and maximum values

In [ ]:
from scipy import stats
arr=np.empty([10,10])
arr=np.random
arr.max()
arr.min()

AttributeError: ignored

### Create a 5 X5  matrix with values 1 ,2, 3, 4 just below the diagnol