# <center> Excercise - NumPy I </center>

### 1. Import the Package under the name np

In [ ]:
import numpy as np

### 2. Print the NumPy version

In [ ]:
np.__version__

'1.19.5'

### 3. Create a 2d Array

In [ ]:
arr=np.array([[1,2,3]])
arr.ndim

2

### 4. Create an Array and find the sqrt, and sin vaules of it

In [ ]:
arr=np.array([1,2,3,4,0,-1])
print(np.sqrt(arr))
print(np.sin(arr))
print(np.cos(arr))
print(np.log(arr))

[1.         1.41421356 1.73205081 2.         0.                nan]
[ 0.84147098  0.90929743  0.14112001 -0.7568025   0.         -0.84147098]
[ 0.54030231 -0.41614684 -0.9899925  -0.65364362  1.          0.54030231]
[0.         0.69314718 1.09861229 1.38629436       -inf        nan]


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:2: RuntimeWarning: invalid value encountered in sqrt
  
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:5: RuntimeWarning: divide by zero encountered in log
  """
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:5: RuntimeWarning: invalid value encountered in log
  """


### 5. Create a 6d Array using ndmin and convert it to Bool Type

In [ ]:
arr=[1,2,3,4,0]
arr6d=np.array(arr,ndmin=6)
print(arr6d)
arr6d.astype('bool')

[[[[[[1 2 3 4 0]]]]]]


array([[[[[[ True,  True,  True,  True, False]]]]]])

### 6. Given the array below, find the dot product of it

In [ ]:
arr1 = np.array([2, 3, 4])
arr2 = np.array([3, 4, 5])
arr=np.dot(arr1,arr2)
print(arr)

38


### 7. Check if All the elements of `arr1` is greater than `arr2`

In [ ]:
arr1>arr2

array([False, False, False])

### 8. given below is an array find the number of rows of the array and the total number of elements

In [ ]:
arr3 = np.array([[1, 2], [2, 3], [3, 4], [5, 6]])
print(np.size(arr3))
print(np.shape(arr3)[0])

8
4


### 9. Create a 3d Array and find its shape

In [ ]:
arr=np.array([1,2,3],ndmin=3)
print(arr)
arr.shape

[[[1 2 3]]]


(1, 1, 3)

### 10. Compare whether arr1 and arr2 are equal ? 

In [ ]:
arr1==arr2

array([False, False, False])