In [99]:
import numpy as np 

In [100]:
np.zeros(100)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [101]:
Z = np.zeros(10)
Z[4]=1
Z

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

In [102]:
np.arange(10,50,1.0)[::-1]

array([49., 48., 47., 46., 45., 44., 43., 42., 41., 40., 39., 38., 37.,
       36., 35., 34., 33., 32., 31., 30., 29., 28., 27., 26., 25., 24.,
       23., 22., 21., 20., 19., 18., 17., 16., 15., 14., 13., 12., 11.,
       10.])

In [103]:
np.arange(9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [104]:
b = np.array([1, 2, 0, 0, 4, 0])
a = np.nonzero(b)

In [105]:
b

array([1, 2, 0, 0, 4, 0])

In [106]:
a

(array([0, 1, 4]),)

In [107]:
b[[0 ,1, 4]]

array([1, 2, 4])

In [108]:
x =  np.random.randn(30)
x#or use random.random()

array([ 0.03398558, -1.96224995,  0.3889317 , -0.89723245,  0.21978417,
        1.71789042, -0.936653  ,  0.36093125,  0.9993023 ,  1.14910863,
        1.46006244,  1.53924702, -0.80510086,  0.70986656, -0.3407243 ,
        0.48293438,  0.20034735, -0.57434936,  0.40599644, -0.85939712,
        0.24972363,  1.17510281,  0.63156568, -0.66613405, -0.14406673,
       -0.67828246, -0.37068628, -0.76988473, -0.79278673,  0.1792316 ])

In [109]:
x.mean()
x.std()

0.864472580681295

In [110]:
a = np.zeros((8,8), dtype = 'float64')

In [111]:
a

array([[0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.]])

In [112]:
a[1::2, ::2] = 1

In [113]:
a[::2, 1::2 ] = 1

In [114]:
a

array([[0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.]])

In [115]:
a = np.ones((10,10))
a[1:-1, 1:-1] = 0
a

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [116]:
np.diag(np.arange(1,5), k= -1)

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

In [117]:
x = np.random.randn(5, 5)
x

array([[-1.05945995, -1.53611562,  0.06159111, -0.56990079, -0.49484034],
       [-0.16603971, -0.21345222, -0.08459281,  1.48011417,  0.28072149],
       [ 1.31240085,  0.35836465,  0.83056946,  0.45222335, -1.35151319],
       [-0.46148648, -0.95212694, -0.47800883, -0.4169341 ,  0.55958153],
       [ 1.20957951,  0.37664469,  0.9690769 , -0.15016044,  0.52591686]])

$Normalise = \frac{x - xmin}{xmax - xmin}$

In [118]:
xmax, xmin = x.max(), x.min()

In [119]:
N = (x - xmin)/(xmax - xmin)

In [120]:
print(N)

[[0.15803029 0.         0.52970325 0.3203386  0.34522412]
 [0.45423459 0.43851546 0.48123748 1.         0.60235368]
 [0.94439637 0.62809547 0.78465013 0.65921336 0.06120304]
 [0.35628225 0.19361545 0.35080444 0.37105313 0.69480686]
 [0.91030701 0.63415603 0.83057084 0.4594992  0.68364568]]


In [121]:
np.unravel_index(100, (6, 7, 8))

(1, 5, 4)

In [122]:
np.unravel_index([22, 41, 37], (8, 7))

(array([3, 5, 5]), array([1, 6, 2]))

In [123]:
x

array([[-1.05945995, -1.53611562,  0.06159111, -0.56990079, -0.49484034],
       [-0.16603971, -0.21345222, -0.08459281,  1.48011417,  0.28072149],
       [ 1.31240085,  0.35836465,  0.83056946,  0.45222335, -1.35151319],
       [-0.46148648, -0.95212694, -0.47800883, -0.4169341 ,  0.55958153],
       [ 1.20957951,  0.37664469,  0.9690769 , -0.15016044,  0.52591686]])

In [124]:

x.ravel()

array([-1.05945995, -1.53611562,  0.06159111, -0.56990079, -0.49484034,
       -0.16603971, -0.21345222, -0.08459281,  1.48011417,  0.28072149,
        1.31240085,  0.35836465,  0.83056946,  0.45222335, -1.35151319,
       -0.46148648, -0.95212694, -0.47800883, -0.4169341 ,  0.55958153,
        1.20957951,  0.37664469,  0.9690769 , -0.15016044,  0.52591686])

In [125]:
x[0][1]

-1.5361156235848237

In [126]:
x[0,1]

-1.5361156235848237

In [127]:
string = 'abcdefghijklmnop'

**create an array consistiing of 100 rows and 10 cols filled with string values in combinations of 3**<br>
Ex = 'abc', 'ade', 'klm'

In [128]:
import random 
cs = []
for i in np.arange(200):
    val = ''.join(random.sample(string,3))
    if val in cs:
        continue
    else:
        cs.append(val)

In [131]:
cs.sort()
np.array(cs).reshape(2,97)

array([['abp', 'acp', 'aef', 'akn', 'ale', 'ani', 'anl', 'anp', 'apj',
        'bad', 'baf', 'bal', 'bao', 'bce', 'bde', 'bea', 'beh', 'bel',
        'bgh', 'bgl', 'bgn', 'bid', 'bjd', 'blo', 'bmg', 'bmj', 'bmo',
        'bna', 'cam', 'cap', 'cba', 'cbe', 'cbj', 'cdg', 'cfi', 'cgo',
        'chf', 'ckb', 'ckd', 'cnl', 'cpb', 'cpo', 'dam', 'dbh', 'dbj',
        'dfb', 'dfe', 'dhm', 'dig', 'dim', 'djg', 'dkj', 'eba', 'ebj',
        'eca', 'ecm', 'edb', 'efh', 'ejb', 'ejm', 'ejp', 'enp', 'eoa',
        'fcg', 'fcl', 'fed', 'fej', 'fge', 'fhe', 'fhg', 'fhi', 'fhn',
        'fid', 'fio', 'fkd', 'fmd', 'fng', 'fob', 'fok', 'fom', 'ghp',
        'gih', 'gmk', 'gna', 'gok', 'gpl', 'hbd', 'hbg', 'hca', 'hcj',
        'heo', 'hep', 'hib', 'hio', 'hkd', 'hmd', 'hmp'],
       ['hpb', 'hpo', 'idb', 'idl', 'ifk', 'igf', 'ijb', 'ikm', 'ilj',
        'ilk', 'imn', 'ina', 'inm', 'iok', 'ipe', 'ipn', 'jah', 'jdg',
        'jei', 'jfh', 'jgn', 'jih', 'jkb', 'jkl', 'jld', 'jme', 'joi',
        'jpa', 'jpc

In [ ]:
np.where(cs == 'cat')

In [ ]:
cs[75,3]

In [ ]:
cs[75]

In [98]:
g_code = []
for i in np.arange(100):
    code = 'G-' + ''.join(random.sample('0123456789',6))
    g_code.append(code)
codes = np.array(g_code).reshape(10,10)
g_code

['G-952036',
 'G-827935',
 'G-024168',
 'G-047536',
 'G-589671',
 'G-724305',
 'G-079526',
 'G-108392',
 'G-347261',
 'G-967215',
 'G-597462',
 'G-478035',
 'G-978265',
 'G-657039',
 'G-306219',
 'G-605392',
 'G-376298',
 'G-240589',
 'G-075423',
 'G-542608',
 'G-863741',
 'G-938067',
 'G-807315',
 'G-148726',
 'G-894017',
 'G-283517',
 'G-275490',
 'G-035916',
 'G-041285',
 'G-859240',
 'G-857094',
 'G-592386',
 'G-067918',
 'G-465908',
 'G-637049',
 'G-920645',
 'G-517436',
 'G-573019',
 'G-276398',
 'G-179548',
 'G-825174',
 'G-594316',
 'G-537814',
 'G-341907',
 'G-870456',
 'G-709864',
 'G-210946',
 'G-675234',
 'G-192870',
 'G-789045',
 'G-632941',
 'G-654130',
 'G-931245',
 'G-972845',
 'G-936785',
 'G-067158',
 'G-271849',
 'G-298105',
 'G-852940',
 'G-389415',
 'G-174965',
 'G-421576',
 'G-329415',
 'G-158260',
 'G-823051',
 'G-287931',
 'G-314709',
 'G-674203',
 'G-523740',
 'G-438270',
 'G-270351',
 'G-530619',
 'G-973206',
 'G-341827',
 'G-213740',
 'G-657081',
 'G-458920',

In [89]:
import pandas as pd

In [96]:
df = pd.DataFrame(codes)[:10]

In [97]:
df

0         1         2   ...        97        98        99
0  G-290385  G-963054  G-759246  ...  G-026873  G-587164  G-248539

[1 rows x 100 columns]

In [132]:
a,b,c = np.unique(codes, return_index= True, return_counts= True)

In [133]:
a[:50]

array(['G-024168', 'G-035916', 'G-041285', 'G-047536', 'G-067158',
       'G-067918', 'G-075423', 'G-079526', 'G-108392', 'G-138467',
       'G-148726', 'G-158260', 'G-159684', 'G-168479', 'G-174965',
       'G-179548', 'G-192870', 'G-210946', 'G-213740', 'G-240589',
       'G-246073', 'G-258940', 'G-270351', 'G-271849', 'G-275490',
       'G-276398', 'G-283517', 'G-287931', 'G-298105', 'G-306219',
       'G-314709', 'G-329415', 'G-341827', 'G-341907', 'G-346071',
       'G-347261', 'G-372610', 'G-376298', 'G-389415', 'G-391578',
       'G-405719', 'G-405729', 'G-421576', 'G-425639', 'G-438270',
       'G-458920', 'G-465908', 'G-473802', 'G-478035', 'G-491067'],
      dtype='<U8')

In [134]:
b[:50]

array([ 2, 27, 28,  3, 55, 32, 18,  6,  7, 87, 23, 63, 85, 80, 60, 39, 48,
       46, 74, 17, 96, 84, 70, 56, 26, 38, 25, 65, 57, 14, 66, 62, 73, 43,
       91,  8, 83, 16, 59, 82, 97, 90, 61, 99, 69, 76, 33, 92, 11, 93])

In [ ]:
c[:50]

In [ ]:
a[5058]

In [ ]:
np.where(codes =='G-015274' )

In [135]:
codes[[84, 235],[7, 8]]

IndexError: ignored

In [ ]:
a[49]

In [136]:
np.where(c>1)

(array([], dtype=int64),)

In [ ]:
np.tile([3],5)

In [ ]:
np.tile(np.array([[0,1],[1,0]]),(4,4))

In [137]:
a = np.arange(9)
a[(a<6) & (a>2)] *= -1
a

array([ 0,  1,  2, -3, -4, -5,  6,  7,  8])

In [ ]:
a[3:6]

In [ ]:
a[-2:]*= -2

In [ ]:
a

In [ ]:
a[a>3]

In [140]:
np.tile([1,2,3], 5)

array([1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])

In [142]:
np.tile(33., 5)

array([33., 33., 33., 33., 33.])